/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.professor;

import dao.profDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.Matricula;
import pessoa.Professor;

/**
 *
 * @author adowt
 */

public class ProfessorView extends javax.swing.JFrame {
    private Professor profAtual;
    /**
     * Creates new form ProfessorView
     */
    public ProfessorView(Professor profAtual) {
        initComponents();
        this.profAtual = profAtual;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAddAula = new javax.swing.JButton();
        jAppFaltas = new javax.swing.JButton();
        jAvalSim = new javax.swing.JButton();
        jProfNome = new javax.swing.JLabel();
        jRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jAddAula.setText("Adicionar aula");
        jAddAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddAulaActionPerformed(evt);
            }
        });

        jAppFaltas.setText("Aplicar faltas");
        jAppFaltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAppFaltasActionPerformed(evt);
            }
        });

        jAvalSim.setText("Avaliar Simulados");
        jAvalSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAvalSimActionPerformed(evt);
            }
        });

        jProfNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jProfNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/aluno-icon.png"))); // NOI18N
        jProfNome.setText("Nome");

        jRegistro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/registro-icon.png"))); // NOI18N
        jRegistro.setText("Registro");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jAppFaltas, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jAddAula, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(192, 192, 192)
                            .addComponent(jAvalSim, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jProfNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jAvalSim, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAppFaltas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddAula, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jAddAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddAulaActionPerformed
        AddAula addAula = new AddAula(this, true, profAtual);
        
        addAula.setVisible(true);
    }//GEN-LAST:event_jAddAulaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            //Quando a janela é criada, preenche o profAtual com o registro correto pois ele vem com null da principalView
            profDAO daoProf = new profDAO();
            profAtual = daoProf.getByLoginSenha(profAtual);
            
            jProfNome.setText(profAtual.getNome());
            jRegistro.setText(profAtual.getRegistro());
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Não foi possível pegar o seu login atual/nErro na conexão!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Não foi possível pegar o seu login atual/nErro no banco!/n"+ex.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void jAvalSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAvalSimActionPerformed
        AvalSimuladosView avalSimul = new AvalSimuladosView(this, true);
        avalSimul.setVisible(true);
    }//GEN-LAST:event_jAvalSimActionPerformed

    private void jAppFaltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAppFaltasActionPerformed
        ApliFaltasView aplFaltas = new ApliFaltasView(this, true, profAtual);
        aplFaltas.setVisible(true);
    }//GEN-LAST:event_jAppFaltasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfessorView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfessorView(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddAula;
    private javax.swing.JButton jAppFaltas;
    private javax.swing.JButton jAvalSim;
    private javax.swing.JLabel jProfNome;
    private javax.swing.JLabel jRegistro;
    // End of variables declaration//GEN-END:variables
}
