/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.alunoDAO;
import dao.profDAO;
import view.aluno.AlunoView;
import dao.usuarioDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import pessoa.Aluno;
import pessoa.Pessoa;
import pessoa.Professor;
import view.atendente.AtendenteView;
import view.professor.ProfessorView;

/**
 *
 * @author adowt
 */
public class PrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public PrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLogin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCadastro = new javax.swing.JButton();
        jLoginButton = new javax.swing.JButton();
        jSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLogin.setToolTipText("");

        jLabel1.setText("Login:");

        jLabel2.setText("Senha:");

        jCadastro.setText("Cadastro");
        jCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastroActionPerformed(evt);
            }
        });

        jLoginButton.setText("Login");
        jLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoginAcao(evt);
            }
        });

        jSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLogin)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLoginButton)
                        .addGap(64, 64, 64)
                        .addComponent(jCadastro))
                    .addComponent(jSenha))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLoginButton)
                    .addComponent(jCadastro))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLoginAcao(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginAcao
        try {
            usuarioDAO usuConnec = new usuarioDAO();
            Pessoa usuario = new Pessoa(jLogin.getText(), jSenha.getText(), "", "", "");
            if (usuConnec.getByLoginSenha(usuario)!=null){                
                usuario = usuConnec.getByLoginSenha(usuario);

                //Pega o tipo de usuário e abre uma tela correspondente
                switch (usuario.getTipo()) {
                    case "Aluno":
                        alunoDAO aluDAO = new alunoDAO();

                        //Pesquisa se o aluno já confirmou sua matrícula ou não
                        if(aluDAO.getByLoginSenha(new Aluno(usuario)) != null) {
                            //Se ele já confirmou sua matrícula a tela abre
                            AlunoView aluTela = new AlunoView();
                            aluTela.setVisible(true);
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(this, "Você precisa confirmar sua matrícula!\n"
                                                                + "Vá até o CFC e insira um saldo com os atendentes!");
                        }                 
                        break;
                    case "Professor":
                        profDAO daoProf = new profDAO();

                        if (daoProf.getByLoginSenha(new Professor(usuario, null)) != null) {
                            Professor prof = new Professor(usuario, null);
                            ProfessorView profTela = new ProfessorView(prof);
                            profTela.setVisible(true);
                            this.dispose();  
                        } else {
                            JOptionPane.showMessageDialog(this, "Seu login ainda não foi confirmado!\n"
                                                                + "Vá até o CFC e converse com os atendentes!");
                        }
                        break;
                    default:
                        AtendenteView atenTela = new AtendenteView();
                        atenTela.setVisible(true);
                        this.dispose();
                        break;
                }
                } else {
                         JOptionPane.showMessageDialog(this, "Login ou senha incorretos!");            
                }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Erro na aplicação!\nContate o desenvolvedor!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro no banco!\n"+ex.getMessage());
        }
    }//GEN-LAST:event_jLoginAcao

    private void jCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroActionPerformed
        CadastroView cada = new CadastroView(null, false);
        
        cada.setVisible(true);
        
    }//GEN-LAST:event_jCadastroActionPerformed

    private void jSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSenhaActionPerformed
        //Se enter for pressionado no campo de senha
        //Executa a ação do botão login
        jLoginAcao(evt);
    }//GEN-LAST:event_jSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jLogin;
    private javax.swing.JButton jLoginButton;
    private javax.swing.JPasswordField jSenha;
    // End of variables declaration//GEN-END:variables
}