/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.aluno;

import javax.swing.JOptionPane;
import pessoa.Aluno;

/**
 *
 * @author adowt
 */
public class AlunoView extends javax.swing.JFrame {
    //A tela recebe um aluno
    Aluno alunoAtual;
    /**
     * Creates new form aluno
     */
    public AlunoView(Aluno alunoRecebido) {
        initComponents();
        //Preenche a variavel criada cima com o aluno recebido
        //Para poder usar suas informações
        this.alunoAtual = alunoRecebido;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JButton jMarcarAula = new javax.swing.JButton();
        jMarcarSimulado = new javax.swing.JButton();
        jAlunoNome = new javax.swing.JLabel();
        jSaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jMarcarAula.setText("Visualizar aulas");
        jMarcarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMarcarAulaActionPerformed(evt);
            }
        });

        jMarcarSimulado.setText("Visualizar Simulados");
        jMarcarSimulado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMarcarSimuladoActionPerformed(evt);
            }
        });

        jAlunoNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jAlunoNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/aluno-icon.png"))); // NOI18N
        jAlunoNome.setText("Nome");

        jSaldo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/saldo-icon.png"))); // NOI18N
        jSaldo.setText("Saldo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jMarcarSimulado, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jMarcarAula, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jAlunoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jAlunoNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMarcarAula, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMarcarSimulado, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMarcarAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMarcarAulaActionPerformed
        MarcarAulaView marcarAula = new MarcarAulaView(this, false, alunoAtual);
        marcarAula.setVisible(true);
    }//GEN-LAST:event_jMarcarAulaActionPerformed

    private void jMarcarSimuladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMarcarSimuladoActionPerformed
        SimuladoAlunoView simuView = new SimuladoAlunoView(this, true, alunoAtual);
        simuView.setVisible(true);
    }//GEN-LAST:event_jMarcarSimuladoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Seta os valores para o aluno recebido no construtor
        jAlunoNome.setText(alunoAtual.getNome());
        jSaldo.setText("R$ "+alunoAtual.getMatricula().getSaldo());
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlunoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlunoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlunoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlunoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlunoView(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAlunoNome;
    private javax.swing.JButton jMarcarSimulado;
    private javax.swing.JLabel jSaldo;
    // End of variables declaration//GEN-END:variables
}
